In [1]:
import numpy

In [2]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
import cv2

In [8]:
smimg=cv2.imread("smallgray.png", 0)

In [9]:
smimg

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
smbgr=cv2.imread("smallgray.png", 1)

In [11]:
smbgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [12]:
cv2.imwrite("newimg.png",smbgr)

True

smimg

In [15]:
smimg[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
for i in smimg:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [18]:
for i in smbgr:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [20]:
for i in smbgr.T:
    print(i)

[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]


In [21]:
smrando = smbgr.T
cv2.imwrite("transposed.png",smrando)

True

In [23]:
for i in smimg.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [24]:
nimg=numpy.hstack((smimg,smimg))

In [25]:
nimg

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [32]:
nimg=numpy.vstack(smbgr)

In [33]:
neimg=numpy.hstack((nimg,nimg,nimg))
neimg

array([[187, 187, 187, 187, 187, 187, 187, 187, 187],
       [158, 158, 158, 158, 158, 158, 158, 158, 158],
       [104, 104, 104, 104, 104, 104, 104, 104, 104],
       [121, 121, 121, 121, 121, 121, 121, 121, 121],
       [143, 143, 143, 143, 143, 143, 143, 143, 143],
       [198, 198, 198, 198, 198, 198, 198, 198, 198],
       [125, 125, 125, 125, 125, 125, 125, 125, 125],
       [255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255],
       [147, 147, 147, 147, 147, 147, 147, 147, 147],
       [209, 209, 209, 209, 209, 209, 209, 209, 209],
       [134, 134, 134, 134, 134, 134, 134, 134, 134],
       [255, 255, 255, 255, 255, 255, 255, 255, 255],
       [ 97,  97,  97,  97,  97,  97,  97,  97,  97],
       [182, 182, 182, 182, 182, 182, 182, 182, 182]], dtype=uint8)

In [34]:
newimg = neimg.T
newimg

array([[187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182],
       [187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
         97, 182]], dtype=uint8)

In [35]:
cv2.imwrite("itsgrowing.png",newimg)

True

In [42]:
list=numpy.hsplit(newimg,3)

In [43]:
list

[array([[187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [46]:
nmpimg = numpy.asarray(list)

nmpimg

In [47]:
nmpimg

array([[[187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143]],

       [[198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147]],

       [[209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182]]], dtype=uint8)

In [53]:
nmpimg = nmpimg.T
nmpimg

array([[[187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143],
        [187, 158, 104, 121, 143]],

       [[198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147],
        [198, 125, 255, 255, 147]],

       [[209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182],
        [209, 134, 255,  97, 182]]], dtype=uint8)

In [58]:
nmpimg = nmpimg.T

In [59]:
nmpimg

array([[[187, 198, 209],
        [187, 198, 209],
        [187, 198, 209],
        [187, 198, 209],
        [187, 198, 209],
        [187, 198, 209],
        [187, 198, 209],
        [187, 198, 209],
        [187, 198, 209]],

       [[158, 125, 134],
        [158, 125, 134],
        [158, 125, 134],
        [158, 125, 134],
        [158, 125, 134],
        [158, 125, 134],
        [158, 125, 134],
        [158, 125, 134],
        [158, 125, 134]],

       [[104, 255, 255],
        [104, 255, 255],
        [104, 255, 255],
        [104, 255, 255],
        [104, 255, 255],
        [104, 255, 255],
        [104, 255, 255],
        [104, 255, 255],
        [104, 255, 255]],

       [[121, 255,  97],
        [121, 255,  97],
        [121, 255,  97],
        [121, 255,  97],
        [121, 255,  97],
        [121, 255,  97],
        [121, 255,  97],
        [121, 255,  97],
        [121, 255,  97]],

       [[143, 147, 182],
        [143, 147, 182],
        [143, 147, 182],
        [143, 147

In [60]:
cv2.imwrite("itsstillgrowing.png",nmpimg)

True